### ISSUE TITLE
Survey and Results

### ISSUE THREAD

**Issue by austinduncan1** [awasserman14/OsteoApp#13]
A major portion of this application is the values survey that will be completed by users, displaying the results of that survey, then generating a list of treatment options based on these results.

Contained in this epic are stories:

- [x] Take Value Survey
- [x] Share survey results

and Task:

- [x] Development logic (algorithm) for generating treatments list based on survey inputs

**Comment by ghost** [comment]
All three stories were accomplished
